### ISSUE TITLE
Synchronization not working with all accounts

### ISSUE THREAD

**Issue by jdsika** [madfish-solutions/templewallet-mobile#549]
Given:
I am a user with Temple wallet as a FIrefox extension on Win10 which includes my imported Ledger accounts as well

When:
I am installing Temple on my android phone and select the "sync" option

Then:
I would expect ALL accounts to be synchronized but only the standard Temple hot wallet is transferred

Cudos on your release :)

**Comment by unixvb** [comment]
Hi, currently Temple Wallet Mobile does not support Ledger.
Will add this in future releases.

**Comment by letier3110** [comment]
Hi, current implementation of sync requires to send encrypted private keys of HD account to phone. Due to security reasons, we have to encrypt QR-code's payload, so its possible size allows only to export 3-10 accounts, which can lead to errors and bad user experience. So currently its possible to sync only HD account.
